version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: furway_postgres_local
    restart: unless-stopped
    environment:
      POSTGRES_USER: unsecureuser
      POSTGRES_PASSWORD: unsecurepassword
      POSTGRES_DB: furway
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
